sudo: required
services:
  - docker

before_install:
  - docker build -t simplygwee/github-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simplygwee/github-complex-test npm test

after_success:
  - docker build -t simplygwee/github-multi-client ./client
  - docker build -t simplygwee/github-multi-nginx ./nginx
  - docker build -t simplygwee/github-multi-server ./server
  - docker build -t simplygwee/github-multi-worker ./worker
  
# Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push simplygwee/github-multi-client
  - docker push simplygwee/github-multi-nginx
  - docker push simplygwee/github-multi-server
  - docker push simplygwee/github-multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env 
  bucket_name: elasticbeanstalk-ap-southeast-1-944427285131
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY